# Generated by Django 5.1.2 on 2024-10-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default='produtos/imagem_padrao.png', upload_to='produtos/'),
        ),
    ]
